name: Cypress Tests

on: [pull_request]

jobs:
  prepare: 
    runs-on: ubuntu-latest
    steps:
      - name: Prepare pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
  install-deps:
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - name: Install packages
        run: pnpm i
  cypress-run:
    runs-on: ubuntu-latest
    needs: [prepare, install-deps]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.x.x # use the explicit version number
        with:
          build: pnpm dev
          start: pnpm test:ci
