name: Cypress Tests

on: [pull_request]

jobs:
  install-deps: 
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: corepack enable && corepack prepare pnpm@latest --activate && pnpm i
  cypress-run:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.x.x # use the explicit version number
        with:
          build: pnpm dev
          start: pnpm test:ci
